spring:
  application:
    name: buggify-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
    initialize: true

  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        show-sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  level:
    com.neookpara.buggify: DEBUG
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: DEBUG